version: '3.3'
services:
  php-fpm:
    container_name: 'boilerplate-php-fpm'
    build:
      context: ./
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - ./:/app
    ports:
      - '9000:9000'
    networks:
      - overlay
  composer:
    container_name: 'boilerplate-composer'
    restart: 'no'
    image: composer/composer:php7
    networks:
      - overlay
    volumes:
      - .:/app
    command: 'install --ignore-platform-reqs'
  db:
   container_name: 'boilerplate-db'
   image: mysql:5.7
   volumes:
     - db-data:/var/lib/mysql
   restart: always
   networks:
     - overlay
   environment:
       - MYSQL_ALLOW_EMPTY_PASSWORD=yes
       - MYSQL_DATABASE=boilerplate
  nginx:
    container_name: 'boilerplate-nginx'
    image: nginx:1.15.5
    ports:
      - '8080:80'
    environment:
      - NGINX_PORT=80
    volumes:
      - ./:/app
      - ./docker/nginx/nginx_app.conf:/etc/nginx/conf.d/app.conf
    networks:
      - overlay
  redis:
    container_name: 'boilerplate-redis'
    image: redis:5.0-rc6
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - '6379:6379'
    expose:
      - '6379'
    networks:
      - overlay
  node:
    container_name: 'boilerplate-node'
    build:
      context: './'
      dockerfile: 'docker/node/Dockerfile'
    working_dir: /app
    environment:
      - NODE_ENV=dev
      - DEV_SERVER_PORT=3001
    volumes:
      - ./:/app
    ports:
      - '3001:3001'
    expose:
      - '3001'
    command: >
      sh -c '
        yarn
        yarn dev
      '
    networks:
      - overlay
volumes:
    db-data:
networks:
    overlay:

